image: node:lts

cache:
  paths:
  - node_modules/

pages:
    script:
    - yarn install
    - echo "PROXY_URL=https://example.com" > .env
    - npx parcel build src/index.html --out-dir public --public-url .

    artifacts:
        paths:
        - public
    only:
    - master
